
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'healthcare_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'healthcare_analytics'

vars:
   wrk_schema: BRONZE
   file_format_csv: HEALTHCARE_ANALYTICS.BRONZE.MY_CSV_FORMAT
   purge_status: FALSE
   stage_name: HEALTHCARE_ANALYTICS.BRONZE.S3_HEALTHCARE_STAGE
   rawhist_db: HEALTHCARE_ANALYTICS

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
models:
  healthcare_analytics:
    example:
        schema: example 
    silver:
        +materialized: table
    gold:
        materialized: view

